### ISSUE TITLE
Mask appearing as a square instead of a circle

### ISSUE THREAD

**Issue by graeme204marble** [frogcat/leaflet-tilelayer-mask#2]
Hi, 

I have been using leaflet-tilelayer-mask for a few months. It has been great so many thanks for making it in the first place!

Recently I've had issues with the mask appearing as a square rather than a circle. Any idea what might be causing that?

Happy to add an extract of code if that helps debug

Graeme

**Comment by frogcat** [comment]
Thank you for letting me know.

I checked <http://frogcat.github.io/leaflet-tilelayer-mask/> and found two problems.

First, overlay images are broken due to  404 Not found. I'll fix it later. It's a simple problem.

Second, I reproduced the problem you mentioned.
Below is screen shot of Chrome/Linux.

![image](https://user-images.githubusercontent.com/12029629/117601264-dc064880-b188-11eb-8a51-38083126e92f.png)

But in case of Firefox/Linux, it seems to work fine.
![image](https://user-images.githubusercontent.com/12029629/117601369-212a7a80-b189-11eb-8b86-f2369da18a3b.png)

I think there were some changes on webkit, which caused the problem. 
I will investigate and follow up.

Thank you again.

**Comment by graeme204marble** [comment]
Thanks for the update! Will keep an eye out for your follow up.

**Comment by frogcat** [comment]
Follow up.

I created minimal code to reproduce problem, and found that luminance based svg mask are broken when used with css transform and translate3d on Chrome/Linux.

![image](https://user-images.githubusercontent.com/12029629/117751391-fbb47400-b24f-11eb-8bf9-98b0d672ee10.png)

See <https://bl.ocks.org/frogcat/bca746d8b3386215b9266710a74ea5e7> for more details.

I think this behavior is related to this bug.
[Bug 200532 - Applying a css matrix3d transform to an SVG containing a mask breaks the mask](https://bugs.webkit.org/show_bug.cgi?id=200532)

Too avoid this problem, there are two simple solutions.

1. use alpha based mask instead of luminance based mask
2. use svg transform instead of css transform

I pushed following commits to implement solutions, and now it works fine for me.

- <https://github.com/frogcat/leaflet-tilelayer-mask/commit/5c51ac77f9fb53b29b144288d430636280c19a68>
- <https://github.com/frogcat/leaflet-tilelayer-mask/commit/07e6b762385eb0bf5264fc19d95d2ba6039100e7>

Please try it.

**Comment by graeme204marble** [comment]
Thanks for the answer. Havent had a chance to test it yet but will do so asap!

**Comment by graeme204marble** [comment]
@frogcat can confirm that it now works. Sorry for the delay and thanks again!
